on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  prepare:
    runs-on: ubuntu-latest
    name: Prepare
    steps:
      - run: npm install -g yarn
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: dep-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-${{ hashFiles( 'yarn.lock' ) }}
      - name: Setup dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: yarn
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: dep-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-${{ hashFiles( 'yarn.lock' ) }}
      - name: Setup dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Lint
        run: yarn lint
